# Generated by Django 5.2.6 on 2025-09-18 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_company_deal_company_uniq_user_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "email"], name="crm_contact_user_id_861d19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["user", "stage"], name="crm_deal_user_id_9c37b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["user", "amount"], name="crm_deal_user_id_d95a60_idx"
            ),
        ),
    ]
