name: CI

on:
  push:
    branches: [ "main", "feat/**", "fix/**", "ci/**" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Test (SQLite) with coverage
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          DATABASE_URL: sqlite:////tmp/ci.sqlite3
          SECRET_KEY: ci-secret
          DEBUG: "False"
        run: |
          pytest --cov=crm --cov-report=term-missing -q
